--use HRMS
--create table Employee
--(
--   uid int identity(1,1),  
--   id varchar(40) primary key,  --员工id
--   name varchar(30) not null,   --姓名
--   sex char(2) not null,   --性别
--   nation char(4) not null,   --民族
--   polstatus char(8) not null,  --政治面貌  
--   borndate varchar(20) not null, --出生日期
--   bodyweight varchar(5) not null, --体重
--   height varchar(5) not null, --身高  
--   nativeplace varchar(10) not null, --籍贯
--   health varchar(10) not null, --健康状况
--   maritalstatus varchar(5) not null,  --婚姻状态
--   bloodgroup varchar(5) not null, --血型
--   idcard varchar(20) not null, --身份证号
--   serveddep varchar(100) not null,  --所属部门
--   foreign key(serveddep) references Department
--)
